---
language: node_js
node_js:
  - '0.10'
services:
  - neo4j
before_script:
  - npm install -g grunt-cli
after_success:
  - ./scripts/deploy-to-heroku.sh
env:
  global:
  - secure: ! 'oMQE0FSPxyi0G/eMlt6NRFfaKuEVQjcY/e28N/lncoIwb8hGylXjnmaQ6/ME
      eicggmI+KJmrDJhz/O2KezoyyBDGABr8RhnilZ5cYQZyvorqsKJfnjw3kClG
      TuLFRS+9XTi17m4ybUJGTYnBBhadX3csDuTuCj8+eh9vmnD9oGM='

